services:
  db:
    image: db
    build: ./db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - app-network
  kartow:
    image: kartow
    build: ./kartow
    volumes:
      - ./kartow/app:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
